### ISSUE TITLE
Please send me a test account 

### ISSUE THREAD

**Issue by liaz-af** [Oreldad/ATalk#1]
I'm not getting the registration confirmation email.

ASAP please

**Comment by Oreldad** [comment]
oreeldad@gmail.com <mailto:oreeldad@gmail.com>
123456

**Comment by liaz-af** [comment]
The user wasn't validated.
I'll try mine again

**Comment by Oreldad** [comment]
I see your user.
Tell me if it doesn’t work ill reset your
password.

**Comment by liaz-af** [comment]
Ok, all good.

Good luck

**Comment by Oreldad** [comment]
Thanks.
